name: simple_pagination
description: A simple Pagination Widget for your Large list of widgets
version: 0.0.2
homepage: https://github.com/Praveen-Aanand/simple_pagination.git
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
